-- =====================================================================
-- SaaS PRODUCT ANALYTICS  |  MySQL 8.0+   |  ONE FILE
-- Dataset: RavenStack SaaS Subscription & Churn (Kaggle, synthetic)
--
-- HOW TO RUN
--   BLOCK 1 (schema)  -> run first (saas_analytics.py can run it for you)
--   then run saas_analytics.py to load the data
--   BLOCK 2 (data-quality checks), BLOCK 3 (views), BLOCK 4 (analysis)
--   -> run in MySQL Workbench, one query at a time (Ctrl+Enter),
--      or the whole file top to bottom after the data is loaded.
-- The Python script splits this file on the "@@BLOCK" markers below,
-- so do not rename those marker lines.
-- =====================================================================


-- @@BLOCK 1: SCHEMA ---------------------------------------------------
CREATE DATABASE IF NOT EXISTS saas_analytics;
USE saas_analytics;

DROP VIEW  IF EXISTS vw_account_360;
DROP VIEW  IF EXISTS vw_monthly_mrr;
DROP VIEW  IF EXISTS vw_churn_reasons;
DROP VIEW  IF EXISTS vw_feature_adoption;
DROP TABLE IF EXISTS product_events;
DROP TABLE IF EXISTS churn_events;
DROP TABLE IF EXISTS support_tickets;
DROP TABLE IF EXISTS feature_usage;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS accounts;

CREATE TABLE accounts (
    account_id       VARCHAR(20)  NOT NULL,
    account_name     VARCHAR(120),
    industry         VARCHAR(50),
    country          VARCHAR(50),
    signup_date      DATE,
    referral_source  VARCHAR(50),
    plan_tier        VARCHAR(30),
    seats            INT,
    is_trial         TINYINT,
    churn_flag       TINYINT,
    PRIMARY KEY (account_id),
    INDEX idx_acc_signup (signup_date),
    INDEX idx_acc_plan (plan_tier)
);

CREATE TABLE subscriptions (
    subscription_id   VARCHAR(20) NOT NULL,
    account_id        VARCHAR(20) NOT NULL,
    start_date        DATE,
    end_date          DATE,
    plan_tier         VARCHAR(30),
    seats             INT,
    mrr_amount        DECIMAL(12,2),
    arr_amount        DECIMAL(12,2),
    is_trial          TINYINT,
    upgrade_flag      TINYINT,
    downgrade_flag    TINYINT,
    churn_flag        TINYINT,
    billing_frequency VARCHAR(20),
    auto_renew_flag   TINYINT,
    PRIMARY KEY (subscription_id),
    INDEX idx_sub_acc (account_id),
    INDEX idx_sub_start (start_date),
    CONSTRAINT fk_sub_acc FOREIGN KEY (account_id) REFERENCES accounts(account_id)
);

CREATE TABLE feature_usage (
    usage_id            VARCHAR(20) NOT NULL,
    subscription_id     VARCHAR(20) NOT NULL,
    usage_date          DATE,
    feature_name        VARCHAR(60),
    usage_count         INT,
    usage_duration_secs INT,
    error_count         INT,
    is_beta_feature     TINYINT,
    PRIMARY KEY (usage_id),
    INDEX idx_fu_sub (subscription_id),
    INDEX idx_fu_date (usage_date),
    INDEX idx_fu_feat (feature_name),
    CONSTRAINT fk_fu_sub FOREIGN KEY (subscription_id) REFERENCES subscriptions(subscription_id)
);

CREATE TABLE support_tickets (
    ticket_id                   VARCHAR(20) NOT NULL,
    account_id                  VARCHAR(20) NOT NULL,
    submitted_at                DATETIME,
    closed_at                   DATETIME,
    resolution_time_hours       DECIMAL(10,2),
    priority                    VARCHAR(20),
    first_response_time_minutes DECIMAL(10,2),
    satisfaction_score          DECIMAL(3,1),
    escalation_flag             TINYINT,
    PRIMARY KEY (ticket_id),
    INDEX idx_st_acc (account_id),
    INDEX idx_st_date (submitted_at),
    CONSTRAINT fk_st_acc FOREIGN KEY (account_id) REFERENCES accounts(account_id)
);

CREATE TABLE churn_events (
    churn_event_id         VARCHAR(20) NOT NULL,
    account_id             VARCHAR(20) NOT NULL,
    churn_date             DATE,
    reason_code            VARCHAR(50),
    refund_amount_usd      DECIMAL(12,2),
    preceding_upgrade_flag TINYINT,
    preceding_downgrade_flag TINYINT,
    is_reactivation        TINYINT,
    feedback_text          TEXT,
    PRIMARY KEY (churn_event_id),
    INDEX idx_ce_acc (account_id),
    INDEX idx_ce_date (churn_date),
    CONSTRAINT fk_ce_acc FOREIGN KEY (account_id) REFERENCES accounts(account_id)
);

-- Synthetic 1M-row event log generated by the Python script (optional)
CREATE TABLE product_events (
    event_id    BIGINT NOT NULL,
    account_id  VARCHAR(20) NOT NULL,
    event_ts    DATETIME,
    event_type  VARCHAR(40),
    PRIMARY KEY (event_id),
    INDEX idx_pe_acc_ts (account_id, event_ts),
    INDEX idx_pe_type (event_type)
);
-- @@END


-- @@BLOCK 2: DATA-QUALITY CHECKS --------------------------------------
USE saas_analytics;

-- 2.1 Row counts of every table
SELECT 'accounts' AS tbl, COUNT(*) AS n FROM accounts
UNION ALL SELECT 'subscriptions', COUNT(*) FROM subscriptions
UNION ALL SELECT 'feature_usage', COUNT(*) FROM feature_usage
UNION ALL SELECT 'support_tickets', COUNT(*) FROM support_tickets
UNION ALL SELECT 'churn_events', COUNT(*) FROM churn_events
UNION ALL SELECT 'product_events', COUNT(*) FROM product_events;

-- 2.2 Accounts flagged churned but with no churn event (flag / log mismatch)
SELECT COUNT(*) AS flagged_churn_no_event
FROM accounts a
LEFT JOIN churn_events c ON c.account_id = a.account_id
WHERE a.churn_flag = 1 AND c.account_id IS NULL;

-- 2.3 Accounts with a churn event but flag = 0
SELECT COUNT(DISTINCT c.account_id) AS event_but_flag_zero
FROM churn_events c
JOIN accounts a ON a.account_id = c.account_id
WHERE a.churn_flag = 0;

-- 2.4 Subscriptions ending before they start
SELECT COUNT(*) AS bad_date_range
FROM subscriptions
WHERE end_date IS NOT NULL AND end_date < start_date;

-- 2.5 Tickets closed before submitted
SELECT COUNT(*) AS bad_ticket_dates
FROM support_tickets
WHERE closed_at IS NOT NULL AND closed_at < submitted_at;

-- 2.6 Null / non-positive MRR on paying subscriptions
SELECT COUNT(*) AS paying_but_zero_mrr
FROM subscriptions
WHERE is_trial = 0 AND (mrr_amount IS NULL OR mrr_amount <= 0);
-- @@END


-- @@BLOCK 3: VIEWS (used by Power BI) ---------------------------------
USE saas_analytics;

-- One row per account with revenue, usage, support and churn facts
CREATE VIEW vw_account_360 AS
SELECT
    a.account_id, a.account_name, a.industry, a.country, a.referral_source,
    a.plan_tier, a.seats, a.signup_date, a.churn_flag,
    s.total_subs, s.current_mrr, s.lifetime_mrr_months,
    COALESCE(u.total_usage, 0)   AS total_usage,
    COALESCE(u.total_errors, 0)  AS total_errors,
    COALESCE(u.features_used, 0) AS features_used,
    COALESCE(t.tickets, 0)       AS tickets,
    t.avg_csat, t.avg_resolution_hrs, COALESCE(t.escalations, 0) AS escalations,
    ce.churn_date, ce.reason_code
FROM accounts a
LEFT JOIN (
    SELECT account_id,
           COUNT(*) AS total_subs,
           SUM(CASE WHEN end_date IS NULL THEN mrr_amount ELSE 0 END) AS current_mrr,
           SUM(TIMESTAMPDIFF(MONTH, start_date, COALESCE(end_date, CURDATE()))) AS lifetime_mrr_months
    FROM subscriptions GROUP BY account_id
) s ON s.account_id = a.account_id
LEFT JOIN (
    SELECT sub.account_id,
           SUM(f.usage_count) AS total_usage,
           SUM(f.error_count) AS total_errors,
           COUNT(DISTINCT f.feature_name) AS features_used
    FROM feature_usage f
    JOIN subscriptions sub ON sub.subscription_id = f.subscription_id
    GROUP BY sub.account_id
) u ON u.account_id = a.account_id
LEFT JOIN (
    SELECT account_id, COUNT(*) AS tickets,
           AVG(satisfaction_score) AS avg_csat,
           AVG(resolution_time_hours) AS avg_resolution_hrs,
           SUM(escalation_flag) AS escalations
    FROM support_tickets GROUP BY account_id
) t ON t.account_id = a.account_id
LEFT JOIN (
    SELECT account_id, MIN(churn_date) AS churn_date, MIN(reason_code) AS reason_code
    FROM churn_events GROUP BY account_id
) ce ON ce.account_id = a.account_id;

-- Monthly MRR with new / churned / net movement (recursive calendar)
CREATE VIEW vw_monthly_mrr AS
WITH RECURSIVE months AS (
    SELECT DATE_FORMAT(MIN(start_date), '%Y-%m-01') AS m FROM subscriptions
    UNION ALL
    SELECT DATE_ADD(m, INTERVAL 1 MONTH) FROM months
    WHERE m < (SELECT DATE_FORMAT(MAX(start_date), '%Y-%m-01') FROM subscriptions)
)
SELECT
    mo.m AS month_start,
    (SELECT COALESCE(SUM(s.mrr_amount),0) FROM subscriptions s
      WHERE s.start_date < DATE_ADD(mo.m, INTERVAL 1 MONTH)
        AND (s.end_date IS NULL OR s.end_date >= DATE_ADD(mo.m, INTERVAL 1 MONTH))) AS active_mrr,
    (SELECT COALESCE(SUM(s.mrr_amount),0) FROM subscriptions s
      WHERE s.start_date >= mo.m AND s.start_date < DATE_ADD(mo.m, INTERVAL 1 MONTH)) AS new_mrr,
    (SELECT COALESCE(SUM(s.mrr_amount),0) FROM subscriptions s
      WHERE s.end_date >= mo.m AND s.end_date < DATE_ADD(mo.m, INTERVAL 1 MONTH)) AS churned_mrr
FROM months mo;

CREATE VIEW vw_churn_reasons AS
SELECT c.reason_code, a.plan_tier, a.industry,
       COUNT(*) AS churn_events, SUM(c.refund_amount_usd) AS refunds
FROM churn_events c JOIN accounts a ON a.account_id = c.account_id
GROUP BY c.reason_code, a.plan_tier, a.industry;

CREATE VIEW vw_feature_adoption AS
SELECT f.feature_name, f.is_beta_feature,
       COUNT(DISTINCT s.account_id) AS accounts_using,
       SUM(f.usage_count) AS total_usage,
       SUM(f.error_count) AS total_errors,
       ROUND(SUM(f.error_count) / NULLIF(SUM(f.usage_count),0) * 100, 2) AS error_rate_pct
FROM feature_usage f JOIN subscriptions s ON s.subscription_id = f.subscription_id
GROUP BY f.feature_name, f.is_beta_feature;
-- @@END


-- @@BLOCK 4: ANALYSIS QUERIES (run one at a time) ---------------------
USE saas_analytics;

-- Q1  Headline KPIs: current MRR, ARR, customers, ARPA, churn rate
SELECT
    ROUND(SUM(CASE WHEN end_date IS NULL THEN mrr_amount END), 0)       AS current_mrr,
    ROUND(SUM(CASE WHEN end_date IS NULL THEN mrr_amount END) * 12, 0)  AS current_arr,
    COUNT(DISTINCT CASE WHEN end_date IS NULL THEN account_id END)      AS active_accounts,
    ROUND(SUM(CASE WHEN end_date IS NULL THEN mrr_amount END) /
          NULLIF(COUNT(DISTINCT CASE WHEN end_date IS NULL THEN account_id END),0), 0) AS arpa
FROM subscriptions;

-- Q2  Overall logo churn rate
SELECT ROUND(AVG(churn_flag) * 100, 2) AS logo_churn_pct FROM accounts;

-- Q3  Churn rate by plan tier, ranked
SELECT plan_tier, COUNT(*) AS accounts, SUM(churn_flag) AS churned,
       ROUND(AVG(churn_flag) * 100, 1) AS churn_pct,
       RANK() OVER (ORDER BY AVG(churn_flag) DESC) AS churn_rank
FROM accounts GROUP BY plan_tier;

-- Q4  Churn rate by industry and referral source
SELECT industry, referral_source, COUNT(*) AS accounts,
       ROUND(AVG(churn_flag) * 100, 1) AS churn_pct
FROM accounts GROUP BY industry, referral_source
HAVING COUNT(*) >= 10
ORDER BY churn_pct DESC LIMIT 20;

-- Q5  Monthly MRR waterfall with month-over-month growth
SELECT month_start, active_mrr, new_mrr, churned_mrr,
       new_mrr - churned_mrr AS net_new_mrr,
       ROUND((active_mrr - LAG(active_mrr) OVER (ORDER BY month_start)) /
             NULLIF(LAG(active_mrr) OVER (ORDER BY month_start),0) * 100, 2) AS mom_growth_pct
FROM vw_monthly_mrr ORDER BY month_start;

-- Q6  Top 10 churn reasons and revenue impact
SELECT reason_code, COUNT(*) AS events,
       ROUND(COUNT(*) * 100 / SUM(COUNT(*)) OVER (), 1) AS pct_of_churn,
       ROUND(SUM(refund_amount_usd), 0) AS refunds_usd
FROM churn_events GROUP BY reason_code ORDER BY events DESC LIMIT 10;

-- Q7  Upgrade / downgrade behaviour and churn
SELECT upgrade_flag, downgrade_flag, COUNT(*) AS subs,
       ROUND(AVG(churn_flag) * 100, 1) AS churn_pct, ROUND(AVG(mrr_amount), 0) AS avg_mrr
FROM subscriptions GROUP BY upgrade_flag, downgrade_flag;

-- Q8  Billing frequency and auto-renew vs churn
SELECT billing_frequency, auto_renew_flag, COUNT(*) AS subs,
       ROUND(AVG(churn_flag) * 100, 1) AS churn_pct
FROM subscriptions GROUP BY billing_frequency, auto_renew_flag ORDER BY churn_pct DESC;

-- Q9  Signup cohort retention (monthly cohorts, months since signup)
WITH cohort AS (
    SELECT a.account_id,
           DATE_FORMAT(a.signup_date, '%Y-%m-01') AS cohort_month,
           COALESCE(ce.churn_date, CURDATE()) AS end_dt, a.signup_date
    FROM accounts a
    LEFT JOIN (SELECT account_id, MIN(churn_date) AS churn_date
               FROM churn_events GROUP BY account_id) ce ON ce.account_id = a.account_id
),
offsets AS (SELECT 0 AS k UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3
            UNION ALL SELECT 6 UNION ALL SELECT 9 UNION ALL SELECT 12)
SELECT c.cohort_month, COUNT(*) AS cohort_size, o.k AS months_since_signup,
       ROUND(SUM(CASE WHEN TIMESTAMPDIFF(MONTH, c.signup_date, c.end_dt) >= o.k
                      THEN 1 ELSE 0 END) / COUNT(*) * 100, 1) AS retained_pct
FROM cohort c CROSS JOIN offsets o
WHERE DATE_ADD(c.signup_date, INTERVAL o.k MONTH) <= CURDATE()
GROUP BY c.cohort_month, o.k ORDER BY c.cohort_month, o.k;

-- Q10 Customer lifetime (months) by plan: average and median-ish (window)
SELECT plan_tier, ROUND(AVG(life_m), 1) AS avg_life_months, COUNT(*) AS accounts
FROM (
    SELECT a.plan_tier,
           TIMESTAMPDIFF(MONTH, a.signup_date, COALESCE(ce.churn_date, CURDATE())) AS life_m
    FROM accounts a
    LEFT JOIN (SELECT account_id, MIN(churn_date) AS churn_date
               FROM churn_events GROUP BY account_id) ce ON ce.account_id = a.account_id
) x GROUP BY plan_tier;

-- Q11 Feature adoption ranking and error rate
SELECT feature_name, accounts_using, total_usage, error_rate_pct,
       DENSE_RANK() OVER (ORDER BY accounts_using DESC) AS adoption_rank
FROM vw_feature_adoption ORDER BY adoption_rank;

-- Q12 Does breadth of feature use protect against churn?
SELECT CASE WHEN features_used = 0 THEN '0'
            WHEN features_used <= 5 THEN '1-5'
            WHEN features_used <= 10 THEN '6-10' ELSE '11+' END AS feature_breadth,
       COUNT(*) AS accounts, ROUND(AVG(churn_flag) * 100, 1) AS churn_pct
FROM vw_account_360 GROUP BY feature_breadth ORDER BY feature_breadth;

-- Q13 Do high error counts precede churn? (quartiles of total errors)
SELECT q AS error_quartile, COUNT(*) AS accounts, ROUND(AVG(churn_flag) * 100, 1) AS churn_pct
FROM (SELECT churn_flag, NTILE(4) OVER (ORDER BY total_errors) AS q FROM vw_account_360) t
GROUP BY q ORDER BY q;

-- Q14 Support: CSAT and resolution time vs churn
SELECT CASE WHEN avg_csat IS NULL THEN 'no tickets'
            WHEN avg_csat < 3 THEN 'CSAT < 3'
            WHEN avg_csat < 4 THEN 'CSAT 3-4' ELSE 'CSAT 4+' END AS csat_band,
       COUNT(*) AS accounts, ROUND(AVG(churn_flag) * 100, 1) AS churn_pct,
       ROUND(AVG(avg_resolution_hrs), 1) AS avg_resolution_hrs
FROM vw_account_360 GROUP BY csat_band;

-- Q15 Ticket priority mix and escalation rate
SELECT priority, COUNT(*) AS tickets,
       ROUND(AVG(escalation_flag) * 100, 1) AS escalation_pct,
       ROUND(AVG(first_response_time_minutes), 0) AS avg_first_response_min,
       ROUND(AVG(satisfaction_score), 2) AS avg_csat
FROM support_tickets GROUP BY priority ORDER BY tickets DESC;

-- Q16 Top 20 accounts by MRR with churn status
SELECT account_id, account_name, industry, plan_tier, current_mrr, churn_flag
FROM vw_account_360 ORDER BY current_mrr DESC LIMIT 20;

-- Q17 At-risk accounts: still active, low usage, unhappy support, many tickets
SELECT account_id, account_name, plan_tier, current_mrr, total_usage, tickets, avg_csat,
       (CASE WHEN total_usage < 500 THEN 1 ELSE 0 END)
     + (CASE WHEN avg_csat < 3    THEN 1 ELSE 0 END)
     + (CASE WHEN tickets >= 5    THEN 1 ELSE 0 END)
     + (CASE WHEN escalations > 0 THEN 1 ELSE 0 END) AS risk_score
FROM vw_account_360
WHERE churn_flag = 0 AND current_mrr > 0
ORDER BY risk_score DESC, current_mrr DESC LIMIT 25;

-- Q18 Activation funnel from the synthetic 1M-row event log
SELECT event_type, COUNT(DISTINCT account_id) AS accounts,
       ROUND(COUNT(DISTINCT account_id) * 100 /
             (SELECT COUNT(DISTINCT account_id) FROM product_events), 1) AS pct_of_accounts
FROM product_events GROUP BY event_type ORDER BY accounts DESC;

-- Q19 Does early activation (event in first 14 days) reduce churn?
WITH first_ev AS (
    SELECT p.account_id,
           MAX(CASE WHEN p.event_ts <= DATE_ADD(a.signup_date, INTERVAL 14 DAY)
                    THEN 1 ELSE 0 END) AS active_first_14d
    FROM product_events p JOIN accounts a ON a.account_id = p.account_id
    GROUP BY p.account_id
)
SELECT f.active_first_14d, COUNT(*) AS accounts, ROUND(AVG(a.churn_flag) * 100, 1) AS churn_pct
FROM first_ev f JOIN accounts a ON a.account_id = f.account_id
GROUP BY f.active_first_14d;
-- @@END
